development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
<<<<<<< HEAD
  channel_prefix: a_production
=======
  channel_prefix: project_production
>>>>>>> 015c8ea324514c24ae5084ddfb046d7fc20b71c3
